添加优秀镜像仓库项目
comwrg/FUCK-GFW pull request #31
Opened 2022-05-07 15:23 UTC by eryajf

鉴于有不少同学可能不方便使用代理，或者企业服务器不方便使用代理，因此创建了[Thanks-Mirror](https://github.com/eryajf/Thanks-Mirror)这个仓库，希望能互补[FUCK-GFW](https://github.com/comwrg/FUCK-GFW)项目。

2022-05-07 15:41 UTC, kang8 requested changes

2022-05-07 15:41 UTC, kang8 commented on README.md
> +  - [git](#git)
此处的 TOC 是自动生成的，故无需修改。 Ref #21

2022-05-07 15:57 UTC, eryajf commented on README.md
> +  - [git](#git)
这里我没有修改，我也奇怪我这边fork之后怎么生成的多了，我再来一次

2022-05-07 16:05 UTC, eryajf commented on README.md
> +  - [git](#git)
复现了，很奇怪我的vscode保存之后自动生成了索引，才导致的这个问题，目前还没找到是插件还是其他设置的原因，我先把这个问题修复掉

![May-08-2022 00-03-16](https://user-images.githubusercontent.com/33259379/167262454-1266549b-29d3-4f7c-bbbd-579486d78aef.gif)

2022-05-07 16:14 UTC, eryajf commented on README.md
> +  - [git](#git)
把vscode重启了之后，该问题消失了，神奇，目前目录问题已修复

2022-05-07 16:16 UTC, eryajf commented on README.md
> +  - [git](#git)
应该是 Markdown All in One 这个插件带来的意外惊喜

2022-05-08 12:42 UTC, merged

2022-05-08 12:43 UTC, comwrg commented
感谢。